vim.g.mapleader = " "

vim.cmd("set expandtab")
vim.cmd("set tabstop=2")
vim.cmd("set softtabstop=2")
vim.cmd("set shiftwidth=2")
vim.cmd("set number relativenumber")
vim.cmd("set scrolloff=8")
vim.cmd("set clipboard+=unnamedplus")

vim.cmd("nnoremap <C-j> <C-w>j")
vim.cmd("nnoremap <C-k> <C-w>k")
vim.cmd("nnoremap <C-h> <C-w>h")
vim.cmd("nnoremap <C-l> <C-w>l")

vim.cmd("nmap <Up>    <Nop>")
vim.cmd("nmap <Down>  <Nop>")
vim.cmd("nmap <Left>  <Nop>")
vim.cmd("nmap <Right> <Nop>")
vim.cmd("map $ <Nop>")
vim.cmd("map ^ <Nop>")
vim.cmd("map { <Nop>")
vim.cmd("map } <Nop>")
vim.cmd("noremap K     {")
vim.cmd("noremap J     }")
vim.cmd("noremap H     ^")
vim.cmd("noremap L     $")
vim.cmd("noremap <C-x> :bp<Bar>bd #<Cr>")

vim.cmd("imap <Up>    <Nop>")
vim.cmd("imap <Down>  <Nop>")
vim.cmd("imap <Left>  <Nop>")
vim.cmd("imap <Right> <Nop>")
vim.cmd("inoremap <C-k> <Up>")
vim.cmd("inoremap <C-j> <Down>")
vim.cmd("inoremap <C-h> <Left>")
vim.cmd("inoremap <C-l> <Right>")

vim.cmd("nmap >> <Nop>")
vim.cmd("nmap << <Nop>")
vim.cmd("vmap >> <Nop>")
vim.cmd("vmap << <Nop>")
vim.cmd("nnoremap <Tab>   >>")
vim.cmd("nnoremap <S-Tab> <<")
vim.cmd("vnoremap <Tab>   >><Esc>gv")
vim.cmd("vnoremap <S-Tab> <<<Esc>gv")


vim.cmd("nnoremap <A-j> :m .+1<CR>==")
vim.cmd("nnoremap <A-k> :m .-2<CR>==")
vim.cmd("vnoremap <A-j> :m '>+1<CR>gv=gv")
vim.cmd("vnoremap <A-k> :m '<-2<CR>gv=gv")
